name: Tests Browser Extension

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: yarn install
        run: yarn install
      - name: yarn test
        run: yarn run test
